spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sql_store?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 121.199.75.6
  cache:
    redis:
      time-to-live: 1000000


mybatis:
  configuration:
    map-underscore-to-camel-case: true

debug: true

